import re
import os

try:
  os.remove('trainer_data.txt')
except OSError:
  pass

f = open('jobs_descriptions.txt', 'r')
t = open('trainer_data.txt', 'a')

words = ["3d animation" , "3d art" , "3d builder" , "3d coat" , "3d desig" , "3d design" , "3d engine" , "3d engine development" , "3d environment artist" ,
 "3d math" , "3d modeling" , "3d modelling" , "3d printer" , "3d studio" , "3d studio max" , "3d studio max html5" , "3dmax" , "3ds max" , "3dsmax" ,
  "3g" , "4gl" , "5 sap implementations" , "5s" , "7" , "70-461 - querying microsoft sql server" , "70-480" , "8\) j2se" , "8i" , "9i" , "a/b tests" ,
  "abalysis" , "abap" , "abap - basics" , "abap cds" , "abap data dictionary" , "ability to conceptually adapt technologies to fit various ideas" ,
  "ability to create data to execution tests" , "ability to meet deadlines." , "abl language" , "access" , "access -  vba" , "accessibility" ,
  "accounting" , "accounts" , "acl" , "acrobat" , "acss" , "acting" , "action script" , "action script 3" , "actions beans" , "actionscript 3" ,
  "active directory" , "activemq" , "activiti developer" , "activity" , "ad words" , "adabas" , "adaptability" , "adaptive computing - moab" ,
  "adcs" , "adf" , "adianti" , "administration of windows server and linux servers." , "administrator network" , "ado.net" , "adobe  illustrator" ,
  "adobe after effects" , "adobe air" , "adobe analytics" , "adobe animate" , "adobe audition" , "adobe cc suite" , "adobe character animator" ,
  "adobe creative suite softwares" , "adobe dreamweaver" , "adobe entity manager 5" , "adobe experience design" , "adobe experience design cc" ,
  "adobe experience manager 6.1" , "adobe fireworks cs6" , "adobe flash" , "adobe flash professional" , "adobe flex" , "adobe illustrator" ,
  "adobe indesign" , "adobe lightroom" , "adobe marketing cloud" , "adobe media encoder" , "adobe media optimizer" , "adobe muse" ,
  "adobe omniture" , "adobe photoshop" , "adobe premiere" , "adobe premiere 13.0" , "adobe suite" , "adobe xd" , "adonis.js" , "adsupport" ,
  "advanced english" , "advanced knowledge in programming visual basic.net and asp.net" ,
  "advanced knowledge of design and execution of tests cases" , "advanced knowledge of utilization of quality center tools." , 
  "advanced skills on computer networks" , "advanced spanish" , "advertising" , "advertising planning" , "advpl" , "adwords" , "aem5" ,
  "aerohive" , "aeronautics" , "aerospike" , "affinity" , "afnetworking" , "after effects" , "agente de monitoramento" , "agile" , 
  "agile & waterfall methodologies" , "agile - intermediate" , "agile and kanban process" , "agile coach" , "agile development methodology" , 
  "agile leadership" , "agile methodologies" , "agile methodology" , "agile project management" , "agile software development" , "agile tester" , 
  "aix" , "ajax" , "ajax - intermediate" , "akka" , "akka.net" , "alamofire" , "alcatel technologies" , "alfresco" , "algolia" , "algorithm" , 
  "algorithms" , "alm" , "also the designer must to be able to thinking about creativity strategies and solutions that takes into account usability" , 
  "altium design" , "always smiling" , "amanda" , "amazing coffee" , "amazon aws" , "amazon ec2" , "amazon ec2 container service" , 
  "amazon web services" , "amcharts" , "american sign language" , "amqp" , "analise de requisitos" , "analisys" , "analitical mind" , "analysis" , 
  "analysis and requirements" , "analysis services" , "analysis: structural and functional" , "analytical and critical thinking skills" , 
  "analytics" , "android" , "android - intermediate" , "android api" , "android app development" , "android basic" , "android developer" , 
  "android development" , "android framework" , "android ndk" , "android scrum" , "android sdk" , "android studio" , "android studio \(begginer\)" , 
  "android volley api" , "angular" , "angular 1" , "angular 2" , "angular 2 basic" , "angular 4" , "angular js" , "angular js \(beginner\)" , 
  "angular material" , "angular ui" , "angular-seo" , "angular.js" , "angular.js - beginner" , "angular2" , "angular2 basic" , "angularjs" , 
  "angularjs \(basic\)" , "angularjs - basic" , "angularjs - intermediate" , "angularmaterial" , "animate cc" , "animation" , "animatronic" , 
  "annotations" , "ansi c" , "ansible" , "ansys" , "ant" , "antispam intel mcafee" , "antispam sms" , "antispam sms jinny enghouse" , 
  "antispam trend micro" , "antivirus protection" , "any programmer language" , "any programming language" , "aop" , "apache" , "apache 2" , 
  "apache 2 - basic" , "apache activemq" , "apache beam" , "apache camel" , "apache cordova" , "apache cxf" , "apache kafka" , "apache karaf" , 
  "apache maven - intermediate" , "apache qpid" , "apache solr" , "apache spark" , "apache storm" , "apache tomcat" , "apache tomcat - advanced" , 
  "apache wicket - advanced" , "apache zeppelin" , "apex" , "apex developer" , "api" , "api design" , "api instagram" , "api man" , "api rest" , 
  "app design" , "appdynamics" , "appgyver" , "appium" , "apple human interface guidelines" , "apple imac" , "apple ipad" , "apple iphone" , 
  "apple ipod" , "apple motion" , "apple scripts" , "apple tv" , "apple watch" , "applets" , "application architect" , 
  "application designer - mit professional education" , "application designer certified by mit professional education program" , 
  "application developer" , "application developer - mit professional education" , 
  "application developer certified by mit professional education program" , "application development for ios and andorid" , "application engine" , 
  "application lifecycle management" , "application management" , "application security" , "application servers" , "application support" , 
  "approach to" , "arabic market" , "arabic: read" , "arangodb" , "arcgis" , "arcgis api javascript" , "archimate" , "architectural patterns" , 
  "architecture" , "architecture analysis" , "architeral patterns" , "archlinux" , "archviz" , "arcserve" , "arduino" , "ariba cloud integration" , 
  "ariba network" , "arm" , "arnold render" , "arquillian" , "arquitect \(outsource system application\)" , "arquitect \(system integration\)" , 
  "arquitetc \(application outsourcing system\)" , "ars remedy" , "art direction" , "art director" , "artcam" , "articulation" , 
  "artificial intelligence" , "artist" , "artist 3d" , "arts; corel draw; vectors; illustrations" , 
  "arts; corel draw; vectors; illustrations \(10+ years\)" , "as400" , "asana" , "asat" , "asic" , "ask me more :\)" , 
  "asp" , "asp .net mvc 5" , "asp.net" , "asp.net - intermediate" , "asp.net ajax control toolkit" , "asp.net core" , "asp.net core mvc" , 
  "asp.net developer" , "asp.net mvc" , "asp.net mvc 3" , "asp.net mvc 5" , "asp.net mvc developer" , "asp.net web api" , "asp.net web forms" , 
  "asp.net-core" , "asp.net-mvc" , "aspnet core" , "aspnet mvc" , "aspose r" , "aspose reports" , "assembler" , "assembly" , "asset recovery" , 
  "asset security" , "assp" , "asterisk" , "asterix" , "astm" , "astrophysics" , "atam - architecture tradeoff analysis method" , "atention to detail" , 
  "atg" , "atom" , "atomic design" , "audio editing" , "audio processing" , "audiotoolbox" , "audity" , "augmented reality" , "aurelia" , "auth0" , 
  "auto cad" , "auto layout" , "autocad" , "autocad 2d" , "autocad 3d" , "autodesk 3ds max" , "autodesk maya" , "autodesk sketchbook" , 
  "automated testing" , "automation" , "automation projects" , "automation test" , "automotive embedded electronic development" , "automotive tests" , 
  "avaya site administration" , "avfoundation" , "aviation" , "avr assembly" , "awk" , "aws" , "AWS" , "aws emr" , "aws lambda" , "aws rds \(mysql\)" , 
  "aws redshift" , "aws s3" , "aws services" , "aws-beginner" , "ax" , "axis2" , "axure" , "ayudante de barra" , 
  "ayudante de carga y descarga de mercancia" , "ayudante de construcion" , "ayudante de refrigeracion" , "azure" , "azure api management" , 
  "b2b" , "b2c" , "b4" , "b4a" , "b4i" , "b4j" , "baan" , "babeljs" , "babok" , "back-end development" , "backbone.js" , "backbonejs" , "backend" , 
  "backend development" , "backendless" , "backlog management" , "backup" , "backup systems" , "backup tools" , "bacula" , "bakup systems" , 
  "balanced scorecard" , "balckbaud cr" , "balsamiq mockups" , "bamboo" , "bank charges" , "banking" , "banking charges" , "banner ads" , 
  "barracuda antispam" , "basecamp" , "bash" , "bash script" , "basic android knowledge" , "basic bpmn" , "basic french" , "basic german" , 
  "basic knowledge of languages c" , "basic knowledge of languages python and r" , "basic linux administration \(debian and redhat\)" , 
  "basic spanish" , "batch classes" , "batch script" , "bcp" , "bdd" , "bdd - behavior-driven development" , "bea weblogic" , "beagle bone black" , 
  "behavior driven development" , "bemcss" , "best practices" , "bgp" , "bi" , "bi architecture" , "bi tools" , "big data" , "Big Data " , 
  "big data concepts" , "big ip" , "bigquery" , "bind9" , "bing maps api" , "biodiesel" , "biometrics" , "birst" , "birt" , "bitbucket" , "bitcoin" , 
  "bitrise" , "biztalk" , "blackbaud crm" , "blackberry" , "blade" , "blazemeter" , "blender 3d" , "blockchain technologies" , "blogging" , 
  "blue dragon" , "bluemix" , "bmc remedy" , "bng" , "boardgame" , "boiler operator" , "bokeh" , "bonita" , "boomi" , "boost" , 
  "boostrap" , "bootstrap" , "bootstrap - basic" , "bootstrap and other front-end frameworks" , "bootstrap templates" , "borland" , "bot framework" , 
  "bots" , "bottle" , "bower" , "box2d" , "bpm" , "bpmn" , "bpmn \(bpm metastorm e-work\)" , "brackets" , "brainstorm" , "brand development" , 
  "branding" , "branding & identity" , "briefing program" , "brocade" , "browserify" , "bscs" , "bsda certification" , "bsda certified" , 
  "budgetary management" , "budgeting" , "bugs" , "bugzilla" , "build automation" , "build pipelines" , "buildroot" , "bullet physics" , 
  "burp suite" , "business administration" , "business analysis" , "business analyssis" , "business and commercial writing" , "business applications" , 
  "business development" , "business foundation" , "business intelligence" , "business management" , "business metrics" , "business modelling" , 
  "business object" , "business oriented" , "business planing" , "business planning" , "business process" , "business process management" , 
  "business profile listing" , "business results oriented" , "business startegy" , "business strategy" , "business travel" , "businnes analysis" , 
  "butter knife" , "butterknife" , "c" , "c #" , "c for microcontroller" , "c sharp" , "c#" , "c# \(web development\)" , "c# - basic" , 
  "c# - intermediate" , "c# and vb.net" , "c# asp.net" , "c# developer" , "c# mvc5" , "c# specialist" , "c# windows application" , "c# winforms" , 
  "c# wpf" , "c#\( asp.net" , "c-sharp" , 
  "ca ehealth" , "ca infrastruture management" , "ca sdm" , "ca spectrum" , "cabeamento estruturado" , "cable modem" , "cache" , 
  "caching methods" , "cacti" , "cad" , "cake php" , "cakephp" , "calabash" , "call manager" , "calypso" , "camel" , "campaigns" , "camtasia" , 
  "canva" , "canvas" , "capacity plan" , "capistrano" , "capm" , "capybara" , "car integration" , "card sorting" , "carrier ethernet" , "carto" , 
  "cartoon" , "cascading style sheets \(css\)" , "cash flow" , "casperjs" , "cassandra" , "catalyst" , "ccai" , "ccda" , "ccdp" , "ccie collabora" , 
  "ccie collaboration" , "ccie written" , "ccna" , "ccna 200-120" , "ccna knowleges" , "ccna r&s" , "ccna secu" , "ccna security" , "ccna video" , 
  "ccna voice" , "ccnp" , "ccnp r&s" , "ccnp service provider" , "ccnp voice" , "ccs3" , "cdi" , "ceh" , "celery" , "centos" , "centreon" , 
  "centura" , "certified agile tester" , "certified ethical hacker" , "certified information systems auditor" , "certified java programmer" , 
  "certified jee architect" , "certified product owner" , "certified safe agilist" , "certified scrum master" , "certified scrum product owner" , 
  "certified tester foundation level" , "cfps" , "chai" , "challenge driven" , "change management" , "changeman" , "channel strategy" , 
  "character animation" , "character art" , "character design" , "check" , "check point" , "checkpoint" , "chef" , "chrome extensions" , 
  "churn management" , "ci/cd automation" , "cics" , "cinema 4d" , "cisco asa" , "cisco call manager" , "cisco certified networking associate" , 
  "cisco equipment knowledge" , "cisco ironport" , "cisco routers" , "cisco switches" , "cisco technologies" , "cisco wireless technologies" , 
  "citrix" , "citrix certified administrator for presentation server" , "civil engineer" , "claims" , "clang" , "clarity" , "classic asp" , 
  "clay sculpt" , "clean architecture" , "clean code" , "clear basic" , "clear case" , "clear os" , "clear quest" , "clipper" , "clojure" , 
  "clojure basic" , "cloud" , "cloud basic knowledge \(azure" , "cloud computer" , "cloud computing" , "cloud66" , "cloudera" , "cloudera impala" , 
  "cloudhub" , "cloudstack" , "cluster" , "cluster service" , "cmake" , "cmd" , "cmg suite" , "cmmi certificate" , "cms" , "cnc" , "coach" , 
  "coaching" , "cobit" , "cobit 5" , "cobit certified" , "cobit foundation certificate" , "cobit foundation certified" , 
  "cobit foundations 4.1 - isaca - completed in 04l/2012" , "cobol" , "cobol/400" , "cocoa" , "cocoa touch" , "cocoapods" , "cocos2d" , 
  "code charge" , "code climate" , "code igniter" , "code review" , "codeception" , "codeiginiter" , "codeigniter" , "codeship" , 
  "coding and modularization" , "coding standards" , "coffeescript" , "cognos" , "cognos bi" , "cold fusion" , "coldfusion" , "collaboration" , 
  "commis chef" , "committed" , "communciation" , "communication" , "communication skills" , "community building" , "community manager" , 
  "community mnager" , "compass" , "competitiveness" , "compliance" , "composer" , "composer and npm" , "compositing" , "comptia a+" , 
  "comptia network+" , "comptia security+" , "computacion basica" , "computer engineer" , "computer forensics" , "computer graphics" , 
  "computer hacking forensics investigation" , "computer maintenance" , "computer network" , "computer networking" , "computer science" , 
  "computer security" , "computer support especialist" , "computer vision" , "compuware data center real user monitoring \(dcrum\)" , 
  "compuware dynatrace" , "comti" , "concept art" , "concurrency" , "configuration management" , "configure equipment with sip protocol - ips phones" , 
  "conflict management" , "conflict resolution" , "conflicts management" , "confluence" , "conocimiento" , "constru" , "construct2" , "consul" , 
  "consultant" , "consulting" , "contabilidad" , "containerization" , "content creator" , "content marketing" , "content strategy" , 
  "continous integration" , "continui" , "continuity plan" , "continuos deployment" , "continuos integration" , "continuous delivery" , 
  "continuous deplument" , "continuous integration" , "continuum" , "contract management" , "contracts analysis" , "control-m" , 
  "conversion rate optimization" , "cooperative" , "copywriting" , "cordova" , "core banking" , "core data" , "core data services" , 
  "core java" , "coredata" , "coreddata" , "coregraphics" , "corel draw" , "corel drawx7" , "corel paradox" , "coreldraw" , "corelocation" , 
  "corona render" , "corona sdk" , "corporate communication" , "corporate development" , "corporate finance" , "corporate loyalty" , 
  "corporate visual identities" , "cost control" , "cost-benefit analysis" , "couchbase" , "couchdb" , "countinous integration" , 
  "courage and determination to change paradigms" , "coverity" , "cpa campaigns" , "cpanel" , "cppcheck" , "cpre" , "cqrs" , "createjs" , 
  "creating personas" , "creative" , "creative direction" , "creative planning" , "creative solutions" , "creative strategy" , "creative suite" , 
  "creative writing" , "creativity" , "credit recovery" , "crisis management" , "critical thinking" , "crm" , "crm 2011/2013" , "cron" , 
  "cross-browser testing" , "crossbar.io" , "crossplatform" , "cruise control" , "cryptography" , "cryptography and network security" , 
  "crystal lang" , "crystal reports" , "csirt" , "csm" , "css" , "css - advanced" , "css - intermediate" , "css 3" , "css basic" , 
  "css/css3" , "css3" , "css3 - \(sass - stylus\)" , "css3 - intermediate" , "css3 animation" , "ctal-ta - test analyst" , "ctfl foundation" , 
  "ctfl foundation agile tester" , "cto" , "cucumber" , "cuda" , "cummins engines" , "cumplir objetivo" , "curl" , "curso de computacion" , 
  "customer contracts analysis" , "customer experience" , "customer management" , "customer oriented" , "customer relationship" , 
  "customer service" , "customer success" , "customer support" , "customs compliance" , "cvs" , "cyber" , "cyber security" , "d3.js" , "dagger" , 
  "dagger 2" , "dansguardian" , "dapper" , "dart" , "dashboarding" , "dashboards for business inteligence" , "data analysis" , "data base" , 
  "data center" , "data entry" , "data integration - enterprise" , "data mart" , "data migration" , "data mining" , 
  "data modeling and systems analysis" , "data presentation" , "data privacy applications" , "data protection" , "data quality" , "data science" , 
  "data service" , "data stage" , "data structures" , "data studio" , "data visualisation" , "data warehouse" , "data-driven development" , 
  "databank \(access" , "databank modeling" , "database acces" , "database administration" , "database administration \(ms sql server\)." , 
  "database design" , "database modeling" , "database programmer" , "database sql server 2000" , "database systems" , "database testing" , 
  "database tuning" , "databases" , "datacard capture manager" , "datacard syntera" , "datacenter virtualization" , "dataflex" , "dataguard" , 
  "datastage etl" , "datastore" , "datawarehouse" , "datazen" , "daz studio 4.9" , "db 2" , "db2" , "dba" , "dba oracle" , "dbunit" , 
  "dc/os" , "dcaa" , "dcm4chee" , "ddd" , "debian" , "decision making" , "dedication to getting facts right" , "deep learning" , "define scope" , 
  "delegate effectively" , "deliverability" , "delivery processes" , "dell poweredge" , "dell servers" , "dell storage" , "delphi" , 
  "delphi for android" , "delphi for ios" , "delphi xe" , "delphi; mysql; firebird; java; oop; linux; shell script;" , "demoiselle" , 
  "dependency injection di" , "deploy" , "desarrollo de controles de supervisor  de materiales" , "desenvolvimento" , "desenvolvimento de sites" , 
  "desenvolvimento web" , "design" , "design datacenter" , "design de interface" , "design mobile" , "design patterns" , 
  "design patterns and web design responsive." , "design thinking" , "design user experience" , "desktop applications" , "detail oriented" , 
  "devart" , "development of documentation pre and post project - use case" , "development of technlo" , "development of technology for education" , 
  "development platforms: ios" , "development platforms:android" , "development siebel" , "devexpress" , "devops" , "devops engineer" , "dfs" , 
  "dft" , "dhcp" , "diagramming" , "dicom" , "digital" , "digital art" , "digital banking" , "digital certificate" , "digital compositing" , 
  "digital design" , "digital forensics" , "digital illustration" , "digital law" , "digital marketing" , "digital marketing strategies" , 
  "digital media" , "digital ocean" , "digital painting" , "digital protect brand" , "digital sculpt" , "digital signature" , "digital strategy" , 
  "digital transformation" , "digitalocean" , "dimensional modeling" , "direc" , "disaster recovery" , "disaster recovery plan" , 
  "distributed systems development" , "django" , "django - beginner" , "django rest" , "dmz" , "dns" , "docker" , "docsis" , "doctrine" , 
  "documentation" , "documentdb" , "documentum" , "dojo" , "domain drive design" , "domain driven design" , "domain in corel draw" , 
  "domain-driven development" , "doo php" , "dotnet core" , "dotnetnuke" , "doubleclick for publishers" , "doxygen" , "draw" , "drawbot" , 
  "drawing" , "drbd" , "dream factory" , "dreamweaver" , "dreamweaver cc" , "dreamweaver cs6" , "driven" , "drone" , "dropbox api" , 
  "dropwizard" , "drupal" , "drupal 7" , "drupal 8" , "dunit" , "duplo" , "dw" , "dwr" , "dynamic" , "dynamic script loader" , "dynamics crm" , 
  "dynamics nav" , "dynamo" , "dynamo db" , "e" , "e-commerce" , "e-commerce and digital marketing management" , "e-discovery" , "e-learning" , 
  "e-mail marketing" , "eams" , "easer of working in a group" , "easy learning" , "easy to learn java programming" , "easytrieve" , "easyui" , 
  "ec2" , "eclipse" , "eclipselink" , "ecm" , "ecmascript" , "ecomer" , "ecommerce" , "eda" , "editorial design" , "edius" , 
  "effective delegation" , "effective written and oral communication skills in multiple languages" , "efficient spanish spoken" , "ehcache" , 
  "eigrp" , "ejabberd" , "ejb" , "ejb 3" , "ejb 3+" , "ejb3" , "ejb3 +" , "elastic beanstalk" , "elastic searc" , "elastic search" , "elasticsearch" , 
  "elastix" , "electron.js" , "electronic" , "electronics engineering" , "elementary os" , "eletric engineering" , "eletrical plans" , "eletricista" , 
  "elixir" , "elixir lang" , "elk stack" , "elm" , "eloquent" , "email marketing" , "email template xhtml" , "embedded devices" , "embedded linux" , 
  "embedded software" , "embedded systems" , "ember-cli" , "ember.js" , "emc vnxe" , "emv" , "encase" , "encounter test" , "encounter timing system" , 
  "endevor" , "endian" , "endomarketing" , "energetic" , "energetic efficiency" , "energy" , "engagement" , "engineer" , "engineering" , 
  "engineering analyst" , "english" , "english - toefl" , "english course" , "ensemb" , "ensemble" , "enterasys technologies" , 
  "enterprise application architecture" , "enterprise architecture" , "enterprise integration patterns \(eip\)" , "enterprise manager" , 
  "enterprise resources planning - erp" , "enterprise risk management" , "enterprise search" , "enthusiast" , "entirex" , "entity framework" , 
  "entity framework 4 / 5" , "entity framework 6" , "entityframework" , "entrepreneurship" , "envers" , "epl2" , "erlang" , "erp" , 
  "erp consultant" , "erp consulter" , "erp consulting" , "erp jdedwards" , "erp jdedwrds toolkit and financial reports" , "erp sap" , 
  "erwin" , "es2015" , "es6" , "es7" , "esb" , "eslint" , "esp8266" , "espresso" , "estimation" , "estimation for sale proposals" , "estrategia" , 
  "esxi vmware vsphere" , "etabs" , "ethereum" , "etl" , "etl technical leader" , "etl using ssis \(sql server 2014 / package\)" , "etom" , "event-b" , 
  "events management" , "evidence tampering" , "exadata" , "excel" , "excel - vba" , "excel advanced" , "excellent organizational skills" , 
  "exchange server multi-tenant" , "executive presentation" , "executive relationship" , "experience design" , "experience in batch process" , 
  "experience in full project lifecycles from new business development to final delivery" , "experience in industry system automation analysis" , 
  "experience in mainframe / front-end integration" , "experience in on-line systems" , "experience in sap modules such as sd" , 
  "experience in the technology industry." , "experience in web application development & site designing" , 
  "experience in writing parallel processing program" , "experience with cobol" , "experience with middleware pi" , "expert it knowledge" , 
  "export" , "express" , "express.js" , "expression language" , "extjs" , "extranet" , "extreme networks" , "extreme programming" , 
  "extremme programmin" , "f#" , "f# \(begginer\)" , "fabric8" , "facebook ads" , "facebook graph api" , "facebook marketing" , "facilitation" , 
  "factory method" , "failover cluster" , "fashion designer and product" , "fast learner" , "fast learning" , "fedora" , "ffmpeg" , "fgfd" , 
  "fiberglass" , "file-aid" , "filenet" , "filezilla" , "filmmaking" , "finacial management" , "final cut" , "finance" , "financeiro" , 
  "findbugs" , "fintech" , "fiori" , "firebase" , "firebird" , "firebird - intermediate" , "firewall" , 
  "firewalls" , "fireworks" , "firmware development" , "fitnesse" , "fix api" , "flash" , "flash animation" , "flash cs6" , "flask" , "flex" , 
  "flexbox" , "flexibility" , "flink" , "floor plan" , "floss" , "flume" , "flux" , "flyway" , "focus on results" , "force.com" , 
  "forecasting" , "foreign trade" , "forestpack" , "forever/pm2" , "forniture design" , "fortinet" , "fortran" , "foundation" , 
  "foundation spring data" , "fox programming" , "fpga" , "fragments" , "framer js" , "framework zk" , "frameworks php" , "fraud detection" , 
  "free hand" , "free software" , "freebsd" , "freecode" , "freemarker" , "freenas" , "freepbx" , "freeswitch" , "french" , "french basic" , 
  "french course" , "frenquency inverter" , "freshdesk" , "friendly" , "frin" , "front end" , "front end web development" , "front-de" , 
  "front-end web development" , "frontend" , "fsrm" , "ftk" , "ftk imager" , "ftp" , "fujitsu eternus storage" , "fujtisu primergy servers" , 
  "full stack" , "fullstack" , "fullstack development" , "function points analysis" , "functional specifications" , "functional testing" , 
  "fuzzy logic" , "galera cluster" , "game art" , "game design" , "game development" , "game maker 1.4" , "game maker studio" , "game mechanics" , 
  "gamification" , "gantt" , "gatling" , "gcd" , "gcfe" , "gcih" , "ge smallworld products" , "geb" , "ged" , "gempac & deepsae" , "genexus 8" , 
  "geoframe" , "geoprocessing" , "geoserver" , "german" , "german course" , "gerrit" , "gfi security" , "gimp" , "gis" , "git" , 
  "git - intermediate" , "git flow" , "git repository" , "gitflow" , "github" , "github page" , "gitlab" , "gitlab-ci" , 
  "glass fish" , "glassfish server" , "glbp" , "glpi" , "glusterfs" , "gnu/linux" , "go lang" , "goal oriented" , "golang" , "golden gate" , 
  "good adaptation in new positions and environments" , "good in teamwork" , "good logic" , "google  app engine" , "google ads" , 
  "google adwords" , "google adwords api" , "google adwords for pharmaceutical industry" , "google analytics" , "google api's" , "google app engine" , 
  "google apps" , "google cloud message" , "google cloud platform" , "google datastore" , "google docs" , "google fusiontable" , "google maps api" , 
  "google mock" , "google play services" , "google pro" , "google protocol buffers" , "google search console" , "google tag manager" , 
  "google tango" , "google test" , "google trends" , "google web designer" , "google web toolkig" , "google web toolkit" , "google webmaster tools" , 
  "google webmasters tools" , "gorilla" , "governance" , "government" , "gpgpu" , "gpo" , "gpu" , "gradle" , "grafana" , "grails" , 
  "graph databases" , "graph theory" , "graphic" , "graphic design" , "graphql" , "graylog" , "great communication" , "great energy" , 
  "great self-esteem" , "green it  citizen" , "green technology" , "grid996" , "gridiculous" , "groovy" , "groovy \(grails\)" , "group policy" , 
  "growth hacking" , "grunt" , "grunt; gulp" , "gsap" , "gson" , "gt.m" , "gtk" , "guava" , "gui developer" , "guice" , "gulf countries" , 
  "gulp" , "gulp/grunt" , "gunicorn" , "gwt" , "h2 database" , "h264 encoding" , "h264 video codec" , "hadoop" , "hair&fur" , "haml" , "hana" , 
  "hana core data services \(cds\)" , "hana sqlscript" , "handlebars" , "handlebarsjs" , "hangfire" , "hapi.js" , "happiness" , "hapro" , 
  "haproxy" , "hard work" , "hard-working" , "hardsurface modeling" , "hardware" , "hardware design" , "hardware integrations" , "haskell \(beginner\)" , 
  "haskellcore" , "hateoas" , "hazelcast" , "hbase" , "hdf5" , "head of software" , "health and safety skills" , "healthcare" , "heartbeat" , 
  "help desk management" , "help desk support" , "helpdesk" , "heroku" , "heuristic evaluation" , "hibernate" , "hibernate - intermediate" , 
  "hibernate 3 and 4" , "high availability" , "high levels of integrity" , "high performance clusters" , "high performance computing" , 
  "high performance systems" , "high performance web sites" , "high poly modeling" , "high-level shading language" , "highcharts" , 
  "highpoly modeling" , "highres sculpting" , "history" , "hive" , "hml" , "holistic view" , "hololens developer" , "honest" , 
  "hootsuite certified professional" , "hornetq" , "hortonworks" , "hp blade servers" , "hp proliant series" , "hp quality center" , "hp routers" , 
  "hp-qtp" , "hp-ux" , "hql" , "hse" , "hsqldb" , "hsrp" , "html" , "html 5" , "html 5 - intermediate" , "html and css" , "html and css intermediate" , 
  "html and front page development" , "html basic" , "html/ css/ javascript" , "html/ html 05" , "html/css" , "html/css/" , "html/css/less" , 
  "html/htm5" , "html/html5" , "html4" , "html4.01" , "html5" , "html5 & css3" , "html5 + css3" , "html5 - advanced" , "html5 and css3" , 
  "html5 css javascript" , "html5/css3" , "http" , "httparty" , "httpunit" , "hubspot" , "hudson" , "human centered design" , "humhub" , 
  "hybernate" , "hybrid app" , "hybris" , "hydraulic systems" , "hydraulic systems up to 10k psi" , "hyper-v" , "hyperion" , "ia" , "ibatis" , 
  "ibeacon" , "ibm - lsf" , "ibm aix administrator" , "ibm bluemix" , "ibm bpm 8.5.x" , "ibm cognos" , "ibm customer analytics" , "ibm datastage" , 
  "ibm db2" , "ibm filenet" , "ibm integration bus" , "ibm lsf" , "ibm maximo" , "ibm message broker" , "ibm mobilefirst" , "ibm mq" , 
  "ibm omnibus" , "ibm rational clear case" , "ibm rational system architect" , "ibm rtc" , "ibm tivoli monitoring" , 
  "ibm tivoli storage manager administrator" , "ibm watson explorer" , "ibm wcm" , "ibm web experience factory" , "ibm websphere" , 
  "ibm websphere portal" , "icefaces" , "icon design" , "icons" , "icontrol f5" , "ida pro" , "idea" , 
  "identify challenges and propose thoughtful solutions" , "identity and access management \(oracle\)" , "identity mana" , "identity server" , 
  "ids/ips" , "ielts band 7" , "ielts band 7.5" , "ihs" , "iiot \(industry 4.0 internert of things\)" , "iis" , "illumination" , 
  "illustration" , "illustrator" , "illustrator cc" , "illustrator cs6" , "ilustrator" , "image manipulation" , "image processing" , 
  "imagmagick" , "imex" , "imovie" , "impala" , "implementation" , "implementation of servers based on asterisk" , "implementation planning" , 
  "implementing datacenters" , "import" , "ims" , "inbound marketing" , "inbound sales" , "incident management" , "incident response" , 
  "indesign" , "indesign cc" , "indesign cs6" , "indesign illustrator photoshop  flash premier after effects blender 3d acrobat" , "indicad" , 
  "industrial design" , "influencer" , "influxdb" , "infographics" , "infolease" , "infor baan/ln" , "infor baan/ln developer" , 
  "informatica power center" , "information architecture" , "information management" , "information retrieval" , "information security" , 
  "information security foundation based on iso iec 27002" , "information system security audit" , "information technology" , "informix" , 
  "infosphere" , "infragistics" , "infrastructure" , "initiative" , "inkscape" , "inno setup" , "innovation" , "innovation management" , 
  "inovator" , "instagram" , "instructor" , "instrumentation." , "insurance" , "intallation of new projects." , "integrated communication" , 
  "integration architecture" , "integration management" , "integration services" , "integration test" , "intel realsense" , "intel xdk" , 
  "intellectual curiosity" , "intellij" , "interaction design" , "interface design" , "interface tests" , "interior design" , "intermediary english" , 
  "intermediate french" , "intermediate knowledge of ms visual studio." , "intermediate knowledge of performance tests \(jmeter\)." , 
  "intermediate spanish" , "internal audit" , "internal control" , "international business" , "international freight" , "international projects" , 
  "internet marketing" , "internet of thing" , "internet of things" , "interoperability" , "interpersonal skills" , "interviews" , "intranet" , 
  "inventor" , "inventory" , "inventory management" , "invision" , "ionic framework" , "ionic2" , "ionicframework" , "ios" , "ios design patterns" , 
  "ios development" , "ios native framework" , "ios; android; windows phone; java; c#;" , "iot" , "ipc" , "ipfw" , "iphone" , 
  "iphone development" , "ipsec" , "iptables" , "iptables and endian firewall\)" , "iptables firewall" , "ipv4" , "ipv6 gold engineer" , 
  "ipython" , "ireb's cpre" , "ireb's cpre-fl" , "ireport" , "ireport - intermediate" , "ireports" , "is-is" , "isa server" , "isa3402 audit" , 
  "isdb-t/dvb-t" , "isim - ibm security identity management" , "iso" , "iso 20000" , "iso 270001" , "iso 27001" , "iso 27002" , 
  "iso 27002 certification" , "iso 38500" , "iso 8583" , "iso 9001" , "iso/iec 27002" , "iss" , "istqb's ctfl" , "it architecture" , 
  "it audit" , "it budget management" , "it consulting" , "it governance" , "it infrastructure" , "it management" , "it operations" , 
  "it outsourcing" , "it project management" , "it risk" , "it security" , "it service management" , "it skills" , "it solution strategic" , 
  "it strategic planning" , "it strategy" , "it support technician" , "it training" , "italian" , "itgc" , "itil" , "itil foundation certified" , 
  "itil managing across the lifecycle \(malc\) - exin - completed in 03/2014" , "itil operational support and analysis certificate" , 
  "itil service capability modules management intermediate \(osa" , "itil service management foundation syllabus 2011 - exin - done in 05/2012" , 
  "itil v3 foundation" , "itsm based on iso/iec 20000" , "ius" , "ius platform" , "j" , "j2ee" , "j2me" , "j2se" , "jackrabbit" , "jackson" , 
  "jade" , "japanese" , "jasmine framework" , "jasminejs" , "jasper reports" , "jasperreports" , "jaspersoft reports" , "java" , 
  "java \(android\)" , "java \(android\) - beginner" , "java \(basics\)" , "java \(j2se" , "java \(play 2\)" , "java -" , 
  "java - \(6" , "java - advanced" , "java 5" , "java 6" , "java 7" , "java 8" , "java and c#." , "java and jadevelopment" , 
  "java android" , "java architect" , "java backend" , "java developer" , "java development" , "java ee" , 
  "java ee 6 web services developer certified" , "java ee developer \(ejb" , "java enterprise edition" , "java frameworks" , "java html" , 
  "java j2ee" , "java me" , "java patterns" , "java platform" , "java portlets" , "java programming language" , 
  "java scjp 6 - sun certified programmer for the java platform" , "java script" , "java sdk 1.5 1.6 1.7 and 1.8" , "java se" , "java security" , 
  "java server faces" , "java server pages" , "java socket" , "java standard edition 6 programmer certified professional" , "java swing" , 
  "java system su" , "java system support" , "java web" , "java8" , "javaee" , "javaee\(jsf \) - basic" , "javafx" , "javascriot" , "javascript" , 
  "javascript - \(coffeescript\)" , "javascript - advanced" , "javascript - intermediate" , "javascript - jquery" , "javascript basic" , 
  "javascript dom" , "javascript; css; html; node; c#; java" , "javase" , "javaslang" , "jax-rs" , "jax-ws" , "jaxb" , "jaxp" , "jbehave" , 
  "jboss" , "jboss 4.2 / 5 / 6" , "jboss 7" , "jboss admin" , "jboss aplication server" , "jboss application server" , "jboss drools" , 
  "jboss eap/wildfly and jboss as" , "jboss for web developers certificate" , "jboss portal" , "jboss seam" , "jcl" , "jdbc" , "jdbc - intermediate" , 
  "jdeveloper" , "jee" , "jee 4/5/6/7" , "jeet" , "jekins" , "jekyll" , "jenkins" , "jenkins - basic" , "jersey" , "jetty" , "jfreechart" , 
  "jfrog artifactory" , "jhipster" , "jinja2" , "jira" , "jira - basic" , "jme - java micro edition" , "jmeter" , "jms" , "jni" , "jongo" , 
  "joomla" , "jpa" , "jpa - intermediate" , "jpa - java persistence api" , "jpa 2" , "jpql" , "jpro" , "jprofiler" , "jquery" , "jquery - intermediate" , 
  "jquery ajax" , "jquery mobile" , "jquery ui" , "jqueryui" , "js" , "js\(electron" , "jscript" , "jse" , "jsf" , "jsf - advanced" , 
  "jsf - javaserver faces" , "jsf 2" , "jsf2" , "json" , "json - intermediate" , "jsp" , "jsp - advanced" , "jsp and servlets" , "jsplumb" , 
  "jspm" , "jsr 286" , "jstl" , "jsx" , "jubula" , "juniper routers" , "juniper srx" , "junit" , "junit - intermediate" , "junity" , "jupyter" , 
  "jva" , "jvm" , "jython" , "kaban" , "kafka" , "kaizen" , "kajka" , "kanbam" , "kanban" , "karma" , "kaspersky manager" , "kendo" , 
  "kendo \(telerik\)" , "kendo mvvm" , "kendoui" , "kenshoo" , "keras" , "kernel development" , "kettle" , "keynote" , "keynote speaker" , 
  "keyshot" , "kibana" , "kicad" , "kinesis" , "kivy" , "knime" , "knockoutjs" , "knowledge in jira tool" , "knowledge in the information area" , 
  "knowledge of autocad and solidworks interface with all office package and applications like word" , "knowledge of uml" , "koajs" , "koala" , 
  "kong" , "kotlin" , "kpi development" , "kubernetes" , "kvm" , "labview" , "lambda expressions" , "lamp" , "lan/wan" , "landing page" , 
  "landmark" , "language c" , "languages: j2se" , "laravel" , "laravel 5" , "large experience in the banking industry" , 
  "large underwater robotics systems knowledge" , "laser engraving" , "latex" , "latin america" , "launch planning and execution" , "layout" , 
  "layout design" , "lazy load" , "ldap" , "lead designer" , "lead developer" , "lead generation" , "leadership" , "leading skills" , 
  "leaflet" , "lean manufacturing" , "lean mindset" , "lean six sigma mindset" , "lean startup" , "leasing & auto finance domain" , 
  "less" , "less / sass" , "less and sass" , "level design" , "libboost" , "libcurl" , "libgdx" , "libgdx - basic" , 
  "liferay" , "lighting" , "lightning components" , "lightroom cc" , "lighttpd" , "link building" , "linkedin" , "linode" , "linq" , 
  "linq - intermediate" , "linux" , "linux - intermediate" , "linux / ubuntu" , "linux advanced" , "linux debian" , "linux developer" , 
  "linux institute professional certified" , "linux kernel" , "linux red hat regex and server monitoring" , "linux servers" , 
  "linux servers administration" , "linux sysadmin" , "linux: ubuntu server" , "liquibase" , "liquid" , "live streaming" , 
  "lived in toronto for 5 months studying english language and working as a cleaner" , "llvm" , "lms" , "load balance" , "load runner" , 
  "localization and cat tools" , "lodash" , "log4j" , "logic pro" , "logistcs" , "logistics" , "logo" , "logo design" , "lombok" , 
  "look dev" , "loopback" , "lotus domino" , "lotus notes" , "love art" , "lowpoly modeling" , "lpic2" , "lpic3" , "lua" , "lubricants oils" , 
  "lucene" , "lucid chart" , "luigi" , "lulowin" , "lumen" , "lvm" , "lxc" , "lync server" , "lync server multi-tenant" , 
  "mac os" , "mac os x el capital" , "mac os x lion" , "mac os x mavericks" , "mac os x mountain lion" , "mac os x snow leopard" , "mac os x tiger" , 
  "mac os x yosemite" , "macaron" , "machine learning" , "macos" , "magento" , "magento 2" , "Magento Developer" , 
  "magento solution specialist certified" , "magneto" , "magnolia" , "mailchimp" , "mainframe" , "mainframe cobol" , "mainframe express" , 
  "maintaining datacenters" , "maintaining networks" , "maintenance and repair" , "maintenance management" , "maintenance printers" , 
  "maintenance routes voip" , "malware analysis" , "mamp" , "managed packages" , "managed service" , "management" , "management 3.0" , 
  "management of networks" , "management of projetct" , "managing budgets" , "mandrill" , "manejo de personal" , "manga studio for illustrations" , 
  "manjaro linux" , "mantis" , "manual testing" , "manufacturing execution system" , "manufacturing knowledge" , "mapbaking" , "mapkit" , 
  "mapreduce" , "marathon" , "mariadb" , "market research" , "marketing" , "marketing analytics" , "marketing and digital marketing plan and management" , 
  "marketing automation" , "marketing communications" , "marketing global" , "marketing operations" , "marketing strategy" , "marko.js" , 
  "marmoset toolbag" , "marvel" , "marvelapp" , "marvelous designer" , "matalab" , "material design" , "material ui" , "material-ui" , "materialize" , 
  "math" , "mathcad" , "mathlab" , "matlab" , "matte painting" , "maven" , "mavlink" , "maya" , "maya autodesk" , "mba" , "mcad" , 
  "mcafee device control" , "mcafee dlp" , "mcafee drive encryption" , "mcafee epo security" , "mcafee hips" , "mcafee siem" , "mcdba" , 
  "mcitp windows 7enterprise administrator" , "mcp - microsoft certified professional - completed in 07/2009" , 
  "mcp windows server" , "mcp." , "mcpd: silverlight developer 4" , "mcpd: web developer 4" , "mcpd: windows phone developer" , 
  "mcps - microsoft certified professional" , "mcps: microsoft certified professional" , "mcsa" , "mcsa 2003" , "mcsa windows server 2012" , 
  "mcsd" , "mcsd - web applications" , "mcsd: web applications" , "mcse" , "mcse data plataform" , "mcse windows server" , 
  "mcse windows server 2012 infrastructure" , "mcso" , "mct" , "mcts" , "mcts: .net framework 4" , "mcts: silverlight 4" , "mdb" , "mdm" , 
  "mean" , "mean stack" , "mechanical design" , "mechatronics" , "media planning" , "medical imaging" , "medium" , "mef cecp" , "mel scripting" , 
  "memcached" , "memory management" , "mencoder" , "mentalray" , "mentawai" , "mentoring" , "mercurial" , "mes" , "mesos" , "message queue" , 
  "metaheuristics" , "metaprogramming" , "metasploit" , "meteor" , "meteorjs" , "methodic" , "microbiome" , "microchip pic" , "microservices" , 
  "microsft mcse" , "microsft skills" , "microsiga/protheus" , "microsoft access" , "microsoft active directory" , "microsoft app-v" , 
  "microsoft ax" , "microsoft certified information technology professional \(mcitp\)" , 
  "microsoft certified it professional windows 2008 server admin - ka solution - done in 03/2012" , "microsoft certified professional" , 
  "microsoft certified system administrator" , "microsoft certified system engineer" , 
  "microsoft certified trainer" , "microsoft crm" , "microsoft deployment toolkit" , "microsoft dynamics" , "microsoft entity framework" , 
  "microsoft excel" , "microsoft exchange 2010" , "microsoft exchange 2013" , "microsoft isa server" , "microsoft message queue" , 
  "microsoft navi" , "microsoft office" , "microsoft office 2007" , "microsoft office 2010" , "microsoft office 2013" , "microsoft office 365" , 
  "microsoft office suite" , "microsoft offices packages" , "microsoft operations management suite" , "microsoft outlook" , 
  "microsoft powerpoint" , "microsoft project" , "microsoft security latin american academy" , "microsoft servers" , "microsoft sharepoint" , 
  "microsoft specialist - c#" , "microsoft specialist - html5 with javascript and css3" , "microsoft sql server" , "microsoft sql server  2016" , 
  "microsoft sql server 2012" , "microsoft sql server 2014" , "microsoft sql server always on \(ha\)" , "microsoft sql server integration services" , 
  "microsoft sql server management studio" , "microsoft ssas" , "microsoft ssis" , "microsoft student partner" , 
  "microsoft system center virtual machine manager 2012 r2" , "microsoft team foundation server" , "microsoft test manager" , "microsoft tmg" , 
  "microsoft visio" , "microsoft visual basic" , "microsoft visual basic 6.0" , "microsoft visual c#" , "microsoft visual studio" , 
  "microsoft windows 10" , "microsoft windows 7" , "microsoft windows 8" , "microsoft windows 8.1" , "microsoft windows 98" , 
  "microsoft windows hyper-v server 2008" , "microsoft windows hyper-v server 2012" , "microsoft windows hyper-v server 2012 r2" , 
  "microsoft windows server 2003" , "microsoft windows server 2003 r2" , "microsoft windows server 2008" , "microsoft windows server 2008 r2" , 
  "microsoft windows server 2012" , "microsoft windows server 2012 r2" , "microsoft windows server administration" , "microsoft windows xp" , 
  "microsoft word" , "microstrategy" , "middle east" , "middleware" , "mifare" , "mifare plus" , "migrating client environment" , 
  "migration tool" , "mikrotik" , "mikrotik router" , "military skill" , "mind mapping" , "mining" , "mips" , "mks" , "mmo" , 
  "mobile application development" , "mobile applications" , "mobile commerce" , "mobile company" , "mobile design" , "mobile development" , 
  "mobile development - android native" , "mobile devices" , "mobile hibrid dev" , "mobile marketing" , "mobile technology" , "mobile-first" , 
  "mochajs" , "mockito" , "mockups" , "model driven architecture" , "model vi" , "modeling" , "modelsim" , "modernizr" , "modo" , "modsecurity" , 
  "mokito" , "mongodb" , "mongoose" , "monit" , "monitoring" , "monitoring systems" , "monodevelop" , "monogame" , "moodle admin" , 
  "moodle development" , "moodle elearning" , "moq .net" , "morphia" , "motif" , "motion builder" , "motion design" , "motion graphics" , 
  "motivate others" , "motivated" , "mpi" , "mpls" , "mps.br" , "mqseries" , "mqtt" , "mrtg" , "ms cluster service" , "ms dynamics ax" , 
  "ms excel" , "ms frontpage" , "ms office" , "ms project" , "ms project server" , "ms sql server" , "ms-project" , "ms-sql" , "msbuild" , 
  "mssql server" , "mstest" , "mtcna - mikrotik certified network associate" , "mudbox 3d" , "mule" , "mule \(esb\)" , "mulesoft" , "mulit-tasking" , 
  "multi-task" , "multicast" , "multidimensional modeling" , "multiplayer server" , "multithreading" , "mumps" , "muse" , "music producer" , 
  "music production" , "mustache" , "mvc" , "mvc - advanced" , "mvc 2" , "mvc 3" , "mvc 4" , "mvc 4 & 5" , "mvc 4 - intermediate" , "mvc 5" , 
  "mvc modeling" , "mvp" , "mvvm" , "my sql" , "mysql" , "mysql - intermediate" , "mysql administrator \(version 5.0" , "mysql database" , 
  "mysqli" , "nagios" , "nancyfx" , "narrative" , "nashorn" , "native brazilian portuguese" , "nativescript" , "natural" , "navigation flow" , 
  "ndk" , "nebosh" , "nebosh - national examination board in occupational safety & health" , "negotiating capacity" , "negotiation" , 
  "negotiation capability" , "neo4j" , "nessus" , "net" , "net " , "net beans" , "net compiler platform" , "netapp" , "netbackup symantec" , 
  "netbeans" , "netconf protocols" , "netcool" , "netezza" , "netflix api" , "netflix oss" , "NetSuite" , "netvault" , "network" , 
  "network administration" , "network administrator" , "network analysis" , "network engineering" , "network engineering / programmer" , 
  "network forensics" , "network infrastructure" , "network programming" , "network protocols" , "network security" , "network security: wireshark" , 
  "network troubleshooting" , "networking" , "networking hardwares" , "networking security" , "networking software" , "networks point to point" , 
  "networks\(modbus and lon works\)" , "neural networks" , "new media" , "new relic" , "nexenta storage" , "nexus" , "nfs" , "nginx" , "nhibernate" , 
  "ninject" , "nintex 2010" , "nintex 2013" , "nis" , "nlb" , "nlb service" , "nlp" , "nltk" , "nmap" , "noc" , "node" , "node js" , "node.js" , 
  "node.js basic" , "nodejs" , "nosql" , "nosql databases" , "novell certified linux administrator" , "novell small business specialist" ,
  "novo skill de teste" , "npm" , "nprinting" , "nservicebus" , "ntop" , "nuget" , "nuke" , "numpy" , "nunit" , "nw.js" , 
  "oauth2" , "obiee" , "object calisthenics" , "object orientation" , "object oriented analysis and design" , "object oriented design" , 
  "object oriented programming" , "object-oriented analysis and design \(ooad\)" , "objective c" , "objective-c" , "oc4j" , "ocean framework" , 
  "octopus deploy" , "odata" , "odbc" , "odi" , "oem 12c - oracle enterprise manager cloud control 12c" , "office 365" , "office 365 add-ins" , 
  "office applications: word" , "office pack" , "office suite integration" , "offshore" , "ogre3d" , "oil & gas" , "oil painting" , "okr" , 
  "olap" , "ollydbg" , "omg certified expert in bpm" , "onbase" , "onesignal" , "online advertising" , "online charging" , "online payment processes" , 
  "onsen ui" , "ontologies" , "oo" , "oocss" , "ood" , "oop" , "oops" , "open edx" , "open esb" , "open source" , "openbd" , "openbravo" , 
  "openbsd" , "opencart" , "opencl" , "opencms 6.x / 7.x / 8.x" , "opencv" , "openedge progress" , "openfire" , "opengl" , "openlayers" , "openmp" , 
  "openocd" , "openoffice" , "openshift" , "opensips" , "openspan" , "openstack" , "openvpn" , "operating systems" , "operations management" , 
  "ops" , "optimizepress" , "oracle" , "oracle - 11i" , "oracle - basic" , "oracle 11g" , "oracle 12c and 11g" , "oracle apex - expert" , 
  "oracle api gateway \(oag\)" , "oracle application-plsql" , "oracle applications framework \(oaf\)" , "oracle bi publisher desktop" , "oracle bpel" , 
  "oracle business intelligence" , "oracle certified business component developer" , "oracle certified expert" , "oracle certified master 11g" , 
  "oracle certified professional" , "oracle commerce" , "oracle data integrator" , 
  "oracle db" , "oracle discoverer" , "oracle e-business suite" , "oracle ebs consultant" , "oracle ebs experience" , "oracle enterprise manager" , 
  "oracle exadata" , "oracle forms" , "oracle golden gate" , "oracle java" , "oracle java ee 6 web component developer expert" , "oracle linux" , 
  "oracle pl/sql" , "oracle rac" , "oracle real application cluster - oracle rac" , "oracle reports" , "oracle repport" , "oracle responsys interact" , 
  "oracle retail" , "oracle rman" , "oracle rtd" , "oracle service bus" , "oracle soa suite" , "oracle sql" , "oracle vm" , 
  "oracle-soa suite" , "orange pi" , "orcad capture and layout" , "organic seo" , "organization and analysis of information" , 
  "organizational skills" , "organized" , "orientdb" , "oriented object" , "orm" , "ormlite" , "osgi" , "ospf" , "ostgres" , "osx" , "otrs" , 
  "ott" , "out of the box" , "outsystems" , "owasp" , "owasp zap" , "owb" , "owl2" , "pabx" , "packer" , "packet filter" , "packetcable" , "pacs" , 
  "padi dive" , "pagemaker" , "pages" , "paint" , "painting" , "palo alto networks" , "pandas" , "paradigm" , 
  "parallel computing \(cuda\)" , "parse-server" , "particle animation" , "partnership" , "pascal" , "pascal scripting" , "passenger" , 
  "passionate about new knowledge" , "patching" , "patience" , "pattern making" , "pattern recognition" , "patterns recognition" , "payara server" , 
  "payments" , "pbr texturing" , "pc maintenance" , "pci" , "pci express" , "pci-dss" , "pcl" , "pdca" , 
  "pdl - development plan leaders - stefanini training - completed 10/2009" , "pdo" , "pdpunit" , "pearl" , "pen and paper" , "pentaho" , 
  "pentaho data integration" , "pentest" , "people management" , "peoplecode" , "peoplesoft" , "percona" , "perforce" , "performance and tuning" , 
  "performance improvement of programs" , "performance optimization" , "performance test" , "performance test planning" , "performance testing" , 
  "performance tunning \(application / infrastructure\)" , "perl" , "perl6" , "personal de mantenimiento" , "personas" , "petrel plugins" , "pf" , 
  "pfsense" , "pgbadger" , "pgbouncer" , "pgpool2" , "phalcon" , "phantom" , "phantomjs" , "phaser.js" , "phaserjs" , "phoenix framework" , 
  "phonegap" , "phonegap \(build/cli\)" , "phonegap-beginner" , "photo retouch" , "photograph" , "photography" , "photoshop" , "photoshop \(beginner\)" , 
  "photoshop cc" , "photoshop cs6" , "photovoltaic" , "php" , "PHP" , "php \(laravel\)" , "php \(zend framework\)" , "php - basic" , "php - intermediate" , 
  "php - sql - javascript - jquery - ajax - html - css" , "php 5" , "php 7" , "php developer" , "php devloper" , "php devloper and security" , 
  "php extension development" , "php mysql javas" , "php symfony" , "php\(zend and symfony\(intermediate\)" , "phpoo" , "phpstorm" , "phpunit" , 
  "physics apis" , "phyton" , "pi system" , "picasso" , "pig" , "pipefy" , "piping" , "pixhawk" , "pixijs" , "pki" , "pki administration" , 
  "pl-sql" , "pl/pgsql" , "pl/sql" , "pl/sql developer" , "pl/sql developer oracle" , "planning poker" , "platform crm: siebel e salesforce" , 
  "play framework" , "playframework" , "plc programming" , "plc's" , "plesk" , "plone" , "plumbing engineer" , "pm" , "pmbok" , "pmd" , "pmi" , 
  "pmi capm certified" , "pmo specialist" , "pmp" , "pmp - project management professional" , "podcasting" , "polycom" , "polymer" , 
  "pomodoro technique" , "port-channel" , "portal" , "portfolio management" , "portuguese" , "portuguese - celpebras" , "portuguese fluent" , 
  "pos systems" , "posgresql" , "post gree" , "post implementation support experience" , "post production" , "postcss" , "postegres" , "postfix" , 
  "postgis" , "postgree" , "postgreesql" , "postgres" , "postgres sql" , "postgresql" , "postgress" , "postifix" , "postman" , "pouchdb" , 
  "power bi" , "power builder" , "power designer" , "power generation" , "power point" , "powerbi" , "powerbuilder" , "powerce" , "powercenter" , 
  "powerpoint" , "powershell" , "powershell scripts" , "ppc" , "praticle" , "pre-sales" , "predicting furure trends" , "predictive analytics" , 
  "premiere" , "premiere pro cc" , "presentation" , "presentation skills" , "prestashop" , "preventive and corretive maintenance" , "preventive maintenance" , 
  "prezi" , "price table maintenance" , "pricing analysis" , "primavera" , "prime faces" , "primefaces" , "primefaces - intermediate" , 
  "primefaces framework" , "primefaces." , "primefaces/richfaces" , "prince 2" , "prince2" , "prince2  foundation certified" , "prince2 certified" , 
  "principle" , "print server" , "printing production" , "proactive" , "probabilistics" , "problem management" , "problem solving" , 
  "problem solving skills" , "procesos de negocio" , "process analysis" , "process improvement" , "process improvement skills" , "process integration" , 
  "process management" , "processing" , "product design" , "product development process" , "product launch: planning and execution" , 
  "product management" , "product owner" , "product templating" , "production support" , "professional scrum master i" , "professor" , 
  "profit center management" , "proftpd" , "program management" , "programmer" , "programmer c#" , "programmer html" , 
  "programmer in delphi" , "programmer in php" , "programmer in visual basic .net" , "programmer java" , "programmer javascript" , 
  "programmer php" , "programmer plsql" , "programmer python" , "programming" , "programming in advpl totvs protheus" , "programming javascript" , 
  "progress" , "progress 4gl" , "progressive enhancement" , "progressive web apps" , 
  "project 2013" , "project coordination" , "project lead" , "project management" , "project management disciplines \(pmbok v4\)" , 
  "project management professional" , "project management tools \(ms project server" , "project manager" , "project maneger" , 
  "project planning" , "prolog" , "prometheus" , "promob" , "proposition development" , "prostgresql" , "proteus" , "protheus" , 
  "protheus advpl \(totvs\)" , "prototype" , "prototypes" , "prototyping" , "protractor" , "protractor.js" , "prottotype" , "provisioning" , 
  "proxmox" , "prtg" , "psd-2-html" , "psm i" , "psql" , "public key infrastructure \(pki\)" , "public policy" , "public sector" , "public speaking" , 
  "pug" , "puppet" , "pure css" , "pusher" , "pushkit" , "putty" , "pycharm" , "pyhton" , "pyramid" , "python" , "python begginer" , 
  "python beginner" , "python/fabric" , "python/zope/plone developing" , "python/zope/plone development" , "pythondjango" , "qa director certified" , 
  "qa tools" , "qlik sense" , "qlik sense desktop" , "qlik sense system adminitrator" , "qlikview" , "qlikview system administrator" , "qmail" , 
  "qmf" , "qml" , "qos" , "qt" , "quality assurance" , "quality assurance of program codes" , "quality center" , 
  "quality control" , "qualtrics" , "quartus" , "quartz" , "quartz - intermediate" , "quasar framework" , "querydsl" , "queues" , "quick learner" , 
  "quickfix" , "quixel" , "r" , "r for statistical computing" , "r programming" , "rabbit mq" , "rabbitmq" , "rackspace" , "rad" , 
  "radioloy information system" , "radius" , "railclone" , "rails" , "raml" , "rancher" , "rapidminer" , "raspberry pi" , 
  "rational application developer" , "rational functional tester" , "rational quality manager" , "rational requisitepro" , "razor" , 
  "razor mvc" , "rbpm" , "rca" , "rcv" , "rdbms" , "rdf" , "rdng \(rational doors next generation\)" , "rds" , "rdz" , "react" , "react native" , 
  "react.js" , "react.js basic" , "reactivex \(rxjava" , "reactjs" , "reactor" , "reading and interpreting technical drawing; metrology" , "realm" , 
  "receptionist" , "recommender systems" , "red hat" , "red hat certified system administrator 100-040-674" , "redes" , "redhat" , "redhat linux" , 
  "redhat virtualization manager" , "redis" , "redmine" , "redshift" , "redux" , "refactoring" , "reframe" , "regression testing" , 
  "regular expressions" , "reinsurance" , "relational database" , "relationship management" , "release management" , "reliable" , "remarketing" , 
  "remote access" , "remote dvr access" , "remote work" , "rendering" , "repair on mac os x servers" , "reporting" , "reporting services" , 
  "reporting services 2016" , "reports" , "requeriments gathering" , "require.js" , "requirejs" , "requirement analysis" , "requirement gathering" , 
  "requirements analysis" , "requirements engineer" , "requirementsanalysis and" , "research" , "research & analysis" , "research&development" , 
  "respectful" , "responsible" , "responsive design" , "responsive development" , "responsive layout" , "responsive web design" , "responsivelayout" , 
  "resque" , "rest" , "rest api" , "rest apis" , "resteasy" , "restfb" , "restful" , "restful - intermediate" , "restful api" , "restful web service" , 
  "restfull" , "restify" , "restkit" , "restlet" , "rests" , "result-oriented" , "retail banking" , "retail communications" , 
  "retail; google adwords; google analytics; google adsense; facebook adsense; social media; market intelligence" , "rethinkdb" , "retopology" , 
  "retrofit" , "revenue forecasting" , "reverse engineering" , "review technical codes" , "revit" , "revit mep" , "rfid" , "rfid - basic" , "rfp" , 
  "rhce" , "rhcsa" , "rhcva" , "rhinocam" , "rhinoceros" , "riak" , "rich faces" , "richfaces" , "richfaces - intermediate" , "rig" , "rigging" , 
  "riot.js" , "rip v2" , "risk analisys" , "risk forecast" , "risk management" , "rman" , "rmi" , "robot creation" , "robot programming" , 
  "robotium" , "roll out" , "roscoe" , "roslyn" , "router" , "routers" , "routing" , "rpal" , "rpc system" , "rpm" , "rpt" , 
  "rrd - round robin database" , "rspec" , "rstudio" , "rtc" , "rtl compiler" , "ruby" , "ruby beginner" , "ruby on rails" , "Ruby on Rails" , 
  "ruby on rails \(begginer\)" , "ruby on rails - advance" , "ruby on rails - intermediate" , "ruby on rails - intermetiate" , "rup" , "rupture" , 
  "russian" , "rust" , "rwd" , "rxandroid" , "rxjava" , "rxscala" , "rxtx" , "rxtx - basic" , "s.o.l.i.d. principles" ,
   "s90.01: fundamental soa & service-oriented computing" , "s90.02: soa technology concepts" , "saas" , "saas \(software as a service\)" , "saiku" , 
   "sails.js" , "sales and client focus" , "sales and client relationship" , "sales engineer" , "sales strategy" , "salesforce" , 
   "salesforce administrator" , "salesforce analytics" , "salesforce cloud consultant" , "salesforce sales cloud consultant" , 
   "salesforce service cloud consultant" , "salesforce.com" , "salient uxt" , "salt" , "samba" , "san" , "sap abap" , "sap abap - basics" , 
   "sap abap developer" , "sap abap developer certified" , "sap analysis for office" , "sap b1" , "sap basis" , "sap best practices" , "sap bi" , 
   "sap bi/bo" , "sap bo" , "sap bo data service" , "sap bopf" , "sap bpc" , "sap bps" , "sap bsc" , "sap business one" , "sap bw" , 
   "sap certification abap with sap netweaver 7.40" , "sap certified consultant" , "sap cpm" , "sap crm" , "sap erp implementation" , 
   "sap fi-co" , "sap fiori" , "sap fs-ri" , "sap gateway" , "sap hana" , "sap implementation" , "sap netweaver" , "sap netweaver gateway" , 
   "sap nfe" , "sap otc" , "sap pi" , "sap pm" , "sap pp" , "sap process integration" , "sap ps" , "sap r3" , "sap rollout" , "sap sd" , 
   "sap security" , "sap sem" , "sap solution manager" , "sap ui5" , "sap wm" , "sap workflow" , "sapui5" , "sas" , "sas di studio" , "sas guide" , 
   "sas miner" , "sas visual analytics" , "sas70" , "sass" , "sass/css3" , "sass/less" , "satellite communications" , "saucelabs" , "sbt" , 
   "scada" , "scaffolding" , "scala" , "scalatra" , "scale agile framework" , "scaled agile" , "scbcd" , "sccm" , "scdjws" , "scea" , 
   "scheduling" , "schema registry" , "schlumberger - eclipse" , "scientific computing" , "scikit-learn" , "scjp" , "scketch" , "scketch up" , 
   "scmad" , "scope management" , "scorm" , "scraping" , "scrapy" , "screen flow" , "script logic" , "scriptcase" , "scripting" , "scripts" , 
   "scritpcase web developer - rad" , "scrum" , "scrum fundamentals certified credential" , "scrum master" , "scrum master certified" , 
   "scrum partitioner" , "scrum product owner certified" , "scrummaster" , "scss" , "scvmm" , "scwcd" , "sdlc audit" , "sdlc practices" , 
   "sdlc practise" , "seam" , "search advertising" , "secure coding" , "secure programming" , "security and risk management" , 
   "security architecture" , "security assessment and testing" , "security awareness program" , "security controls" , "security officer" , 
   "security operations" , "security+" , 
   "selenium" , "selenium ide" , "selenium webdriver" , "self-motivated" , "self-taught" , "sem" , "semantic ui" , "semantic web" , 
   "sencha \(extjs\)" , "sencha test" , "senior graphic design 6+ years" , "sensitive" , "seo" , "sequelize" , "serious games" , 
   "server administration" , "server administration printers" , "server less" , "server monitoring" , "server side swift" , "server4you" , 
   "serverless" , "service design" , "service desk" , "service management" , "service mix" , "servicenow" , "servlets" , "servlets - advanced" , 
   "sfml" , "shadding" , "shading" , "shared services" , "sharepoint" , "sharepoint 2010" , "sharepoint 2013" , "sharepoint designer" , "shell" , 
   "shell script" , "shell scripts" , "shellscript" , "shin" , "shiny" , "shopify" , "shopifyapi" , "shorewall" , "sidekiq" , "siebel" , 
   "siebel developer" , "siem" , "signal processing" , "signalr" , "sikuli" , "silex" , "silktest" , "silverlight 4" , "simple text" , 
   "simulation" , "simulink" , "sinatra" , "singleton" , "sinon" , "sip" , "sistem integration arquitect" , "site map" , "six sigma" , "sizing" , 
   "sketch" , "sketch app" , "sketchapp" , "sketchup" , "skype for business" , "slack" , "slackware" , "slb ocean framework" , "slemma" , 
   "slim" , "sling" , "slsb singleton and mdb messages" , "smacss" , "smacss; bemcss; oocss" , "smart cities" , "smart-restart" , "smartcard" , 
   "smartcloud" , "smartplant 3d" , "smartplant electrical" , "smartplant foundation" , "smartplant instrumentation" , "smartplant p&id" , 
   "smartwatch" , "smarty" , "smarty template engine" , "smm" , "smooks" , "smooth streaming" , "snapsvg" , "snarf" , "snmp" , "snort" , "soa" , 
   "soa and ppo\) - exin - done in 12/2013" , "soap" , "soap - intermediate" , "soapui" , "social marketing" , "social media" , 
   "social media coordinator" , "social participation" , "socket.io" , "software architectre" , "software architecture" , 
   "software configuration management" , "software designer" , "software developer" , "software development" , "software development lifecycle \(sdlc\)" , 
   "software development using biometry" , "software development: agile development" , "software engineering" , "software installation" , 
   "software quality assurance" , "software security" , "software technical support analyst" , "software testing" , "softwareag webmethods" , 
   "solaris" , "solid" , "solid edge" , "solid knowledge of sap netweaver and hana studio" , "solid principles" , "solidworks" , "solr" , 
   "solution architect" , "solutions architecture" , "solving complex technical problems in a systematic way" , "sonar" , "sonarqube" , 
   "sonicwall" , "sony audio forge" , "sony vegas" , "sophos utm - proxy security" , "sophos webfiltering" , "soql" , "sound designer" , 
   "soundforge" , "source fire" , "sourcetree" , "sox" , "spam control" , "spanish" , "spanish - mother tongue" , "spanish course" , 
   "spark" , "spark-sql" , "sparql" , "sparx systems enterprise architect" , "speak english" , "speak spanish" , "specflow" , 
   "specialist web development with php" , "specs" , "sphinx" , "splunk" , "spock" , "spock framework" , "spotfire" , "spree commerce" , 
   "spring" , "spring amqp" , "spring batch" , "spring boot" , "spring cloud" , "spring data" , "spring framework" , 
   "spring framework/mvc/webservices" , "spring integration" , "spring jdbc" , "spring jpa" , "spring mail" , "spring mvc" , 
   "spring mvc - intermediate" , "spring security" , "spring security - intermediate" , "spring social facebook" , "spring social twitter" , 
   "spring webmvc" , "spring webservices" , "spring-batch framework" , "springmvc" , "spss" , "sql" , 
   "sql \(mysql" , "sql - avanced" , "sql - basic" , "sql - intermediate" , "sql and oracle pl/sql developer" , "sql and pl/sql tuning" , 
   "sql databases" , "sql development" , "sql query" , "sql server" , "sql server - basic" , "sql server - intermediate" , "sql server 2008" , 
   "sql server 2012" , "sql server 2014" , "sql server analysis server" , "sql server cluster" , "sql server integration server" , 
   "sql server integration services" , "sql server t-sql" , "sql tuning" , "sql-server" , "sqlalchemy" , "sqlite" , "sqllite" , "sqlserver" , 
   "sqoop" , "sqr" , "sqs test" , "squid" , "squid proxies" , "squid proxy" , "ssae16" , "ssas" , "sse" , "ssh" , "ssis" , "ssl" , 
   "ssl certificates" , "sso" , "ssrs" , "stakeholder management" , "startups" , "stash" , "stata" , "statistical in" , "statistics" , 
   "stb" , "sterling integrator b2b" , "stlc" , "stoplight.io" , "storage" , "storage logistics" , "stored procedure \(mysql\)" , "storekeeper" , 
   "storekit" , "storm" , "storyboard" , "storytelling" , "strategic mind" , "strategic planning" , "strategic planning competencies" , 
   "strategy" , "strict adherence to safety requirements" , "strong ability to identify" , "strong background in client/server programming" , 
   "strong background in programming language  .net-c# " , "strong communication skills" , "strong consulting and needs assessment skills" , 
   "strong critical thinking skills." , "strong knowledge and experience architecting enterprise it solutions" , "strong leadership" , 
   "strong reliability" , "strong team work spirit" , "strong time" , "strong work ethic." , "structs" , "structured cabling" , "struts" , 
   "struts mvc" , "struts2" , "study to cissp" , "stupid kiss solid" , "stylus" , "stylus " , "sublime text" , "sublime text 3" , 
   "substance designer" , "substance painter" , "subversion" , "subversion \(tortoisesvn\)" , "successfactors" , "sugar" , "sugarcrm" , 
   "sun certified java programmer" , "sun certified web component developer" , "supervisor" , "supervisory skills" , "suport" , "supply chain" , 
   "support" , "support analyst" , "support developers" , "support tests" , "support web aplication" , "supportive" , "svn" , 
   "svn - intermediate" , "swagger" , "swift" , "swift basic" , "swift developer" , "swing" , "switching" , "switchs layer 2 and 3" , "sybase" , 
   "symantec antispam" , "symantec data loss prevention" , "symantec endpoint" , "symfony" , "symfony 1.4" , "symfony 2" , "symfony 3" , 
   "symfony\(intermediate\)" , "symphony" , "synthesis" , "syslog" , "sysml" , "system adiministration" , "system administration" , 
   "System Administration" , "system administrator" , "system analysis" , "system analyst" , "system architect" , "system center" , 
   "system center family" , "system developer" , "system development" , "system engineer" , "system engineering" , "system integration" , 
   "system verilog" , "systemc" , "systemjs" , "systems analist" , "systems cummins ..." , "systems integration" , "systemverilog" , 
   "t-sql" , "tableau" , "tableau desktop" , "tableau server" , "tableless" , "tacacs" , "taffydb" , "talend studio" , "tam" , "tape" , 
   "target achievement oriented." , "targit" , "task runner: grunt" , "tastypie" , "tasy" , "tax receiver" , "tcl" , "tcp-ip" , "tcp/ip" , 
   "tcpdump" , "tdd" , "tdd - intermediate" , "teaching" , "team foundation server" , "team leadership" , "team management" , "team player" , 
   "team work spirit" , "team worker" , "teamcity" , "teamwork" , "teamwork oriented" , "technical architect" , "technical documentations" , 
   "technical lead" , "technical leadership" , "technical recruitment" , "technical responsible" , "technical skills" , "technical support" , 
   "technology planning" , "tecnico de soporte" , "tef" , "telecom networks" , "telecommunication" , "telegram" , "telepot" , "telerik" , "temboo" , 
   "tensorflow" , "teradata" , "terminal server" , "terminal/bash" , "terracotta" , "terraform" , "tesseract" , "test automation" , "test case" , 
   "test design" , "test driven development" , "test link" , "test management" , "test planning and test script" , "test unit" , 
   "test-driven development \(tdd\)" , "testcomplete" , "testing" , "testlink" , "testng" , "text processing" , "texturing" , "tfs" , "the kdd" , 
   "theano" , "theorical knowledge in hadoop ecosystem" , "theorical knowledge in machine learning algoritms" , "think outside the box" , 
   "threat analysis" , "three.js" , "threejs" , "throubleshoot" , "thymeleaf" , "tibco" , "tika" , "timber" , 
   "time-management and team work skills." , "timing analysis" , "tina" , "tinybsd" , "titanium" , "tm1" , "tmg server" , "togaf" , 
   "tomcat" , "tomcat server" , "tools programmer" , "topology" , "tornado" , "torque" , "tortoise" , "tortoise svn" , "totvs protheus" , 
   "totvs rm" , "trac" , "trade marketing" , "trademarketing" , "trainer" , "training in risk analysis - risk manager - done in 10/10" , 
   "transact-sql" , "transactsql" , "transformati" , "translator" , "transparent" , "travis ci" , "travis-ci" , "travis-cl" , "trello" , 
   "troubleshooting" , "trustworthiness & ethics" , "tslint" , "tsm" , "tso ispf" , "tsql" , "tuleap" , "tunning sql queries" , "turbogears" , 
   "turi" , "tv broadcast data" , "tv broadcast data service" , "tvos" , "twig template engine" , "twitter ads" , "twitter api" , 
   "twitter bootstrap" , "typescript" , "typo3" , "typography" , "uav" , "ubiquiti" , 
   "ubuntu" , "ubuntu server" , "ucd and devops" , "uft" , "ui" , "ui bootstrap" , "ui design" , "ui-router" , "ui/ux design" , "uikit" , "ukrainian" , 
   "umbraco" , "uml" , "uml - intermediate" , "undertown" , "uniface" , "unified communications" , "unified process" , "unit testing" , 
   "unit tests" , "unity" , "unity 2d" , "unity 3d" , "unity ios" , "unity3d" , "unity3d - basic" , "unity5" , "universal windows platform" , "unix" , 
   "unix shell scripting" , "unix system administration" , "unreal" , "unreal engine" , "unreal engine blue print" , "urbancode" , "usability" , 
   "usability testing" , "usb" , "use case" , "user acceptance testing" , "user centered design" , "user experience" , "user experience design" , 
   "user feedback" , "user flows" , "user interface" , "user interface design" , "user interface to brazilian" , "user journey" , "user research" , 
   "user stories" , "user story priorization" , "user tests" , "user-centered design" , "user-experience design" , "uv layout" , "uvm" , "uwp" , 
   "ux" , "ux / ui design" , "ux design" , "ux designer" , "ux ui design \(studying\)" , "v model development" , "v-model" , "v-ray" , "vaadin" , 
   "vagrant" , "vanilla js" , "vapor" , "varnish" , "varnish cache" , "varonis" , "vas" , "vb.net" , "vb6" , "vba" , "vbscript" , "vcenter" , 
   "vectior" , "vector art" , "vector illustration" , "vectorization" , "velocity" , "verification" , "verilog" , "version controll" , "vertica" , 
   "vfx" , "vhdl" , "video editing" , "video network specialist" , "video processing" , "video producer" , "video production" , "videoconferencing" , 
   "vignette cms" , "vimscript" , "viper" , "virtual reality" , "virtual-dom" , "virtualization" , "visio" , "vision in product design" , 
   "visual basic" , "visual basic \(excluding vb.net & vba\)" , "visual basic .net" , "visual basic 6" , "visual brand identity" 
   "visual code studio" , "visual dataflex 7" , "visual design" , "visual force" , "visual fox pro" , "visual identities" , "visual storytelling" , 
   "visual studio" , "visual studio 2010" , "visual studio 2015" , "visual studio code" , "visual studio online \(ci\)" , "visual studio sdk" , 
   "visualforce" , "visualvm" , "vlan" , "vmware" , "vmware administration" , "vmware esx" , "vmware esxi" , "vmware server" , "vmware workstation" , 
   "voice acting" , "voip" , "voip elastix" , "volley" , "volunteer work" , "vpls" , "vpn" , "vraptor" , "vray" , "vrrp" , "vsam" , "vsix" , 
   "vsphere" , "vss" , "vsts" , "vsual force" , "vtex" , "vtk" , "vue.js" , "vuejs" , "vulnerability assessment" , "vulnerability management" , 
   "vxworks" , "w3c" , "wamp" , "wan" , "warehouse" , "was" , "watchos" , "water survival and swing rope training" , "watercolor" , 
   "watercolor painting" , "waterfall methodology" , "wave analytics" , "wbs chart" , "wcf" , "weasis" , "web ana" , "web analytics" , "web api" , 
   "web application message" , "web application messaging protocol" , "web application security" , "web application testing" , "web applications" , 
   "web architecture" , "web crawling" , "web design" , "web design responsive" , "web designer" , "web developer" , "web development" , 
   "web dynpro abap" , "web forms" , "web hosting administration" , "web maps" , "web optimization" , "web performance" , "web programmer" , 
   "web project management" , "web scrapping" , "web semantic" , "web server" , "web servers administration: apache" , "web service soap" , 
   "web services" , "web sockets" , "web standards" , "web-api" , "webapi" , "webdesign" , "webdev" , "webdriver" , "webdynpro" , "webforms" , 
   "webgl" , "webkit" , "weblogic" , "weblogic server" , "webmethods for bpm developers" , "webmin" , "webpack" , "webrtc" , "websense" , 
   "webservices" , "webservices - basic" , "website administration" , "website development" , "websites" , "websocket" , "websockets" , "websphere" , 
   "websphere application server" , "websphere datapower" , "websphere liberty profile" , "websphere mq" , "websphere portal server" , 
   "webwriting" , "weka" , "well-oriented thoughtfulness" , "wep api" , "white hat link building" , "whm" , "wicket" , "wildfly" , 
   "willingness to undertake new goals" , "willpower" , "wind energy" , "windev" , "windowns" , "windows" , "windows - intermediate" , 
   "windows 7 administration" , "windows 98-10" , "windows administration" , "windows and linux servers" , "windows azure" , "windows client" , 
   "windows communication foundation" , "windows deployment server" , "windows developer" , "windows drivers" , "windows forensics" , 
   "windows forms" , "windows mobile" , "windows phone" , "windows phone development" , "windows platform" , "windows presentation foundation" , 
   "windows server" , "windows server 2008" , "windows server 2008 r2" , "windows server 2012" , "windows server 2012 r2" , "windows server 2016" , 
   "windows server administration" , "windows servers" , "windows services" , "windows syadmin" , "windows system administration" , "wireframe" , 
   "wireframing" , "wireless" , "wireless embedded systems" , "wireless pear to pear and pear to multi pear" , "wireshark" , "wix.com" , "wlan" , 
   "wmlscript" , "woocommerce" , "word" , "wordpress" , "work experience with people from different nationalities" , "work well under pressure" , 
   "work well with others" , "work with foundation" , "work with jquery framework" , "work with laravel framework." , "workflow" , 
   "workforce management" , "working globally" , "working in groups" , "working with tools and machinery" , "world machine" , "wpf" , "wpf." , 
   "wps" , "writing" , "writing scenarios" , "ws-bpel" , "wsdl" , "wso2as" , "wso2emm" , "wso2is" , "wsus" , "wxpython" , 
   "x86-64 assembly" , "xamarin" , "xamarin forms" , "xaml" , "xampp" , "xbox" , "xcat" , "xcelsius" , "xcode" , "xcode server" , "xctest" , 
   "xd" , "xen" , "xenapp" , "xenserver" , "xhtml / html" , "xml" , "xml - intermediate" , "xml/schema design" , "xmlbeans" , "xmpp" , 
   "xna" , "xp programming" , "xpath" , "xquery" , "xsd" , "xsl" , "xslt" , "xstl" , "xstream" , "xtream" , "xtreme switches" , "xunit" , 
   "yarn" , "yeoman" , "yii" , "yii framework" , "yii2" , "yml" , "yocto project" , "youtube ads" , "youtube api" , "youtube content specialist" , 
   "z/os" , "zabbix" , "zbrush" , "zbrush sculpting" , "zend framework" , "zend framework 2" , "zend server" , "zend studio" , 
   "zendesk administrator" , "zendframework 2" , "zeplin" , "zeromq" , "zimbra" , "zookeeper" , "zope/plone administration" , "zos" , "zsh" , 
   "zurb foundation" , "zxing" ]

'''
words = ['Software Engineering', 'Management','Design','HTML','Project Management','Microsoft Office','Microsoft Excel','Business Development',
'Unity','Sales','C','Microsoft','Marketing Management','Software','Adobe Photoshop','Microsoft Windows','Research','Microsoft PowerPoint','Microsoft Word',
'Networking','English language','Planning','Training','Web Technologies','Consulting','Product Development','Leadership','WEB','Advertising',
'Business Strategy','Information Technology','Integrity','Customer Service','Quality Assurance','Git','Documentation','Oracle','Test','C#','Security',
'Matlab','Product Management','Support','Customer Relationship Management','Hindi Language','Adobe','Retail','Email','Strategic Planning',
'Sales and Marketing','Social Media Marketing','Communication Skills','Human Resources','Engineering','Market Research','Inventory','Accounting',
'Video','Agile','Services','Adobe Illustrator','Wordpress','Distribution','Automation','Business Analysis','Budgeting','Eclipse','Infrastructure',
'E-Commerce','Microsoft SQL Server','Account Management','Software Development','XML','Web Development','Logistics','French language','Pricing',
'Manufacturing','Scheduling','Project Manager','Graphic Design','Microsoft Access','Coding','Business Operations','Microsoft Outlook','Quality',
'Forecasting','Unix','AJAX','Problem Solving','Recruiting','Insurance','SAP','HTML5 & CSS3','Social Media','Team Player','Process Improvement',
'Microsoft Visual Studio','SCRUM','ASP.NET','Communications','Adobe Indesign','Twitter Bootstrap','Product Marketing','JSON','Audit',
'Technical Support','Salesforce','Public Relations','Financial Analysis','Google Analytics','User Experience Design','Financial','Entrepreneurship',
'Internet','Supply Chain Management','Sourcing','Troubleshooting','Amazon Web Services','Angular.JS','Jira','Procurement','AngularJS',
'Digital Marketing','Real Estate','Marketing Strategy','HR','Due Diligence','Payroll','Risk Management','Spring','Web Applications',
'Business Intelligence','Java J2EE','Lead Generation','Statistics','German Language','REST','Autocad','Github','Purchasing','Billing','Mvc',
'Bootstrap','Account Manager','CMS','Windows XP','Electronics','Compensation and Benefits','Svn','Content Management','Quality Control','Css3',
'Wireless','Telecommunications','User Interface','Layout','Perl','Ecommerce','Windows 7','Test Cases','Bilingual','Apache Tomcat',
'Operations Management','Science','SDLC','Hibernate','PC','Architect','iOS Development', 'Android development','UI/UX Design','Financial Services',
'Visio','Hardware Engineering','Business Requirement gathering','Entertainment','SPSS','Microsoft Visio','Merchandising','Messaging',
'Product Design','Publishing','Cisco','Inventory Management','Branding','Web Services','Dreamweaver','API','Presentation Skills','Business Analyst',
'Flash','Debugging','Microsoft Project','Filing','Objective-C','Data Entry','Time Management','SAS','Teamwork','Business Plan',
'Research and Development','Public Speaking','Tableau','Application Development','Software Testing','Program Management','Microsoft Exchange',
'Finance','NodeJS','Autodesk Autocad','Writing','Swift','Transportation','New Business Development','Team Lead','Apple','Web Design',
'Selenium','React.js','Netbeans','Vendor Management','HTTPS','Visual Basic','User Interface Design','MBA','Adobe Creative Suite',
'Financial Modeling','Compliance','Competitive Analysis','Photography','JDBC','SEO/SEM','Drafting','SharePoint','Email Marketing',
'Monitoring','JUNIT','Cold Calling','Copy Writing and Editing','Packaging','Multimedia','Outsourcing','Brand Management','Object Oriented Programming',
'Product Strategy','Automotive','Publications','Unit Testing','Buying','SQLite','Quickbooks','Financial Statements','Version Control',
'data management','Event Management','Adobe After Effects','Coaching','Sales Strategy and Management','Medical','Licensing','Shell Scripting',
'Analytical skills','HTML/CSS/PHP/MYSQL','Illustration','Adobe Premiere','Russian language','Start-Ups','Mac OS X','Regression Testing',
'Jenkins','Sports','Software Architecture','ITIL','Business Planning','Marketing','Focus','Legal','Xcode','Travel','Bloomberg','Maven',
'Asset Management','Robotics','Tamil language','marathi language','Event Planning','Servers','P&L','Content Marketing','Sales Management',
'Mining','Pharmaceutical','Program Manager','Embedded Systems','Design Patterns','Servlets','Call Center','Negotiation','Use Cases',
'Business Strategies','Product Launch','Data Warehouse','Inside Sales','Private Equity','Business Management','Problem Solving Skills',
'Test Plans','Visual Design','HP','Professional Services','Statistical Analysis','IBM DB2','Digital Media','Reliability','Arabic Language',
'Blogging','Financial Reporting','Online Marketing','DBMS','Venture Capital','Attention to Detail','Functional Testing',
'Leadership and Team Inspiration','RDBMS','Team Building','Sketch','Sales Training','SDK','Apache Hadoop','OOP', 'Agile methodology','POS',
'Utilities','Cascading Style Sheet (CSS)','Investment Banking','Web Analytics','Portfolio Management','Enterprise Software','Tableau Software',
'Mobile Application Design','Accounts Payable','noSQL','Express.js','Project Leader','Verilog','Content Strategy','Acquisitions',
'Google Adwords','Solidworks','Administrative Assistant','Financial Management','Oracle 10g','Technical Writing','PMP','Scrum Master',
'Active Directory','Wholesale','Routers','Construction','Sales Support','User Research','Creative Direction','Angular','Struts','VHDL',
'Strategic Partnerships','Integration Testing','System Design','Talent Acquisition','CRM','People Management','Quality Management','Fabrication',
'Growth Hacking','Apache Maven','Firewall','Mechanical Engineering','Change Management','Economics','Microsoft Active Directory','Drupal',
'SEO','Creative Writing','Microsoft Visual Basic','SaaS','Information Security','Quick Books','Artificial Intelligence','System Administration',
'Securities','Logo Design','Microsoft .NET','Excellent Communication Skills','Redhat','Disaster Recovery','Interface Design','Software Design',
'Heroku','Fraud','Metrics','JSON', 'XML', 'HTML', 'Javascript', 'Java', 'JQuery','Agile Project Management','Unified Modeling Language','Front-End Development',
'Analytics & Reporting','LESS','Hive','Japanese Language','docker','Adobe Acrobat','JBoss','Photoshop','Creative Problem Solving',
'Social Networking','Cfo','Help Desk','Network Security','IBM','Typing','Process Management','System testing','Consultative Sales','Recruiter',
'Nginx','TDD','Control Systems','Relationship Building','Root Cause Analysis','Virtualization','Requirements Analysis','Media Relations',
'Written communication','MS Office','Proofreading','Risk Assessment','Scala','Clustering','Ansys','Lotus Notes','Mobile','Strong Work Ethic',
'Fluent in Spanish','Lean Startups','User Acceptance Testing','Full Stack Development','Git','Distributed Systems','Scripting Languages',
'Subversion','Ant','Copywriting','Stored procedures','Citrix','Project Coordinator','Cross-Functional Team Leadership','Test Automation',
'Wireframing','CVS','Retention','Outside Sales','Chemistry','Leadership Development','agile methodologies ','Wireshark','VMware',
'Management Consulting','Imaging','Inventory control','Kanban','Middleware','IBM Websphere','Frontend Development','accounts receivable',
'Codeigniter','PeopleSoft','Consumer Products','Confluence','JOOMLA','Derivatives','Reconciliations ','Sales/Marketing and Strategic Partnerships',
'Rapid Prototyping','Content Creation','Startups','Firmware','Talent Management','Ms Project','Crystal Reports','Mobile Application Development',
'Risk Analysis','Performance Testing','TFS','Video Editing','Interaction Design','Electrical Engineering','Algorithms & Data Structures',
'Apache Spark','Chef','Social Media Strategy','Sass','Golang','RESTful Services', 'Object-Oriented']
'''
'''
words = ['android studio', 'android', 'angular js', 'angular', 'angularjs', 'arduino', 'assembly', 'aws', 'azure', 'c#', 'c', 
'coffeescript', 'cordova', 'eclipse', 'elixir', 'erlang', 'flask', 'hadoop', 'hibernate', 'intelij', 'ionic', 'ios', 'ipython', 'java', 
'javascript', 'jpa', 'jsf', 'jupyter', 'linux', 'mac os', 'mongodb', 'mssql', 'mysql', 'net core', 'node js', 'node', 'nodejs', 'objective-c', 
'oracle', 'php', 'phpstorm', 'postgres', 'pycharm', 'python', 'r studio', 'r', 'raspberry', 'react native', 'react', 'redis', 'ruby', 
'rubymine', 'scala', 'sinatra', 'spark', 'spring', 'sql server', 'sql', 'sqlite', 'swift', 'typescript', 'vb.net', 'vba', 'vim', 'visual basic', 
'visual studio code', 'visual studio', 'vscode', 'webpack', 'wordpress', 'xcode']
'''
for line in f:
  line_temp = re.sub(r'\b({})\b'.format(('|').join(words)), r' <START:skill> \1 <END> ', line, flags=re.I)
  t.write(line_temp)

t.close()
f.close()  
